services:
  db:
    image: postgres:15
    container_name: pokewiki_db
    restart: always
    environment:
      POSTGRES_USER: zago
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: pokewiki
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pokewiki_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin 
    ports:
      - "8080:80" 
    depends_on:
      - db

volumes:
  postgres_data: